// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api_types

import (
	"encoding/json"
	"time"
)

// Data defines model for Data.
type Data struct {
	// ProductId product id
	ProductId string `json:"product_id"`

	// QuantitySold quantity of items sold
	QuantitySold uint64 `json:"quantity_sold"`

	// SaleDate date and time of sale
	SaleDate time.Time `json:"sale_date"`

	// SalePrice price of sale
	SalePrice json.Number `json:"sale_price"`

	// StoreId store id
	StoreId string `json:"store_id"`
}

// StatisticsRequest defines model for StatisticsRequest.
type StatisticsRequest struct {
	// EndDate starting date for statistics calculation
	EndDate time.Time `json:"end_date"`

	// Operation operation name. possible values: `total_sales`
	Operation string `json:"operation"`

	// StartDate starting date for statistics calculation
	StartDate time.Time `json:"start_date"`

	// StoreId store id
	StoreId string `json:"store_id"`
}

// StatisticsResponse defines model for StatisticsResponse.
type StatisticsResponse struct {
	// EndDate date of the last sale in period
	EndDate time.Time `json:"end_date"`

	// StartDate date of the first sale in period
	StartDate time.Time `json:"start_date"`

	// StoreId store id
	StoreId string `json:"store_id"`

	// TotalSales total of all the sales for the period
	TotalSales json.Number `json:"total_sales"`
}

// PostV1CalculateJSONRequestBody defines body for PostV1Calculate for application/json ContentType.
type PostV1CalculateJSONRequestBody = StatisticsRequest

// PostV1DataJSONRequestBody defines body for PostV1Data for application/json ContentType.
type PostV1DataJSONRequestBody = Data
